# Generated by Django 4.2.4 on 2023-09-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ferramentas2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ativa', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'BD Ferramentas Cadastradas2',
                'verbose_name_plural': 'BD Ferramentas Cadastradas2',
                'db_table': 'db_ferramentas_cadastradas2',
            },
        ),
    ]
