# Generated by Django 4.2.4 on 2023-09-07 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minha_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ferramentas2',
        ),
    ]
